apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  labels:
    app: evaluation-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      containers:
      - name: evaluation-service
        image: evaluation-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: MIN_PAYLOAD_SIZE
          value: "10" # Override for production to configure 1KiB minimum.
        - name: OPENROUTER_MODEL
          value: "deepseek/deepseek-r1-0528:free" # Override for production to configure model.
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: evaluation-service-secrets
              key: openrouter-api-key
        resources:
          requests:
            memory: "50Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
spec:
  selector:
    app: evaluation-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
# Note: Secret is created automatically by 'make minikube-deploy' using OPENROUTER_API_KEY environment variable
